/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/adicionar-curso`; params?: Router.UnknownInputParams; } | { pathname: `/adicionar-disciplina`; params?: Router.UnknownInputParams; } | { pathname: `/agendamento`; params?: Router.UnknownInputParams; } | { pathname: `/agendamentos-dia`; params?: Router.UnknownInputParams; } | { pathname: `/agendar`; params?: Router.UnknownInputParams; } | { pathname: `/atribuir-aula`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-usuario`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/notificacoes`; params?: Router.UnknownInputParams; } | { pathname: `/remover-curso`; params?: Router.UnknownInputParams; } | { pathname: `/remover-disciplina`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/tornar-fixo`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/usuarios`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/adicionar-curso`; params?: Router.UnknownOutputParams; } | { pathname: `/adicionar-disciplina`; params?: Router.UnknownOutputParams; } | { pathname: `/agendamento`; params?: Router.UnknownOutputParams; } | { pathname: `/agendamentos-dia`; params?: Router.UnknownOutputParams; } | { pathname: `/agendar`; params?: Router.UnknownOutputParams; } | { pathname: `/atribuir-aula`; params?: Router.UnknownOutputParams; } | { pathname: `/cadastro-usuario`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/notificacoes`; params?: Router.UnknownOutputParams; } | { pathname: `/remover-curso`; params?: Router.UnknownOutputParams; } | { pathname: `/remover-disciplina`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/tornar-fixo`; params?: Router.UnknownOutputParams; } | { pathname: `/user`; params?: Router.UnknownOutputParams; } | { pathname: `/usuarios`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/adicionar-curso${`?${string}` | `#${string}` | ''}` | `/adicionar-disciplina${`?${string}` | `#${string}` | ''}` | `/agendamento${`?${string}` | `#${string}` | ''}` | `/agendamentos-dia${`?${string}` | `#${string}` | ''}` | `/agendar${`?${string}` | `#${string}` | ''}` | `/atribuir-aula${`?${string}` | `#${string}` | ''}` | `/cadastro-usuario${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/notificacoes${`?${string}` | `#${string}` | ''}` | `/remover-curso${`?${string}` | `#${string}` | ''}` | `/remover-disciplina${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/tornar-fixo${`?${string}` | `#${string}` | ''}` | `/user${`?${string}` | `#${string}` | ''}` | `/usuarios${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/adicionar-curso`; params?: Router.UnknownInputParams; } | { pathname: `/adicionar-disciplina`; params?: Router.UnknownInputParams; } | { pathname: `/agendamento`; params?: Router.UnknownInputParams; } | { pathname: `/agendamentos-dia`; params?: Router.UnknownInputParams; } | { pathname: `/agendar`; params?: Router.UnknownInputParams; } | { pathname: `/atribuir-aula`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-usuario`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/notificacoes`; params?: Router.UnknownInputParams; } | { pathname: `/remover-curso`; params?: Router.UnknownInputParams; } | { pathname: `/remover-disciplina`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/tornar-fixo`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/usuarios`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
